### ISSUE TITLE
[question] YourUpload and Zipyshare

### ISSUE THREAD

**Issue by xellDart** [jordyamc/Animeflv#761]
Can you help me, how to extract direct video link from this websites, please helpme

**Comment by jordyamc** [comment]
In case of YourUpload AnimeFLV have an internal API that returns a JSON containing the direct file link

ZippyShare is other story, in order to download directly from this you have to pass not only the file link, but also the referer (the original link), the user agent (the same that oppened the referer) and the cookie given by the referer (JSESSIONID), for the final file link you have to append part of the referer link plus the solved math problem given in Javascript(in all downloads is the same, only changes the 3 main variables), like this

Referer: www3.zippyshare.com/v/rfdX45/file.html

Final link: www3.zippyshare.com/d/rfdX45/##solved math##/downloadfile.mp4

You can see all this steps here:
https://github.com/jordyamc/Animeflv/blob/master/app/src/main/java/knf/animeflv/zippy/zippyHelper.java

**Comment by xellDart** [comment]
creo que los dos hablamos español, XD, muchas gracias por responder, estoy realizando una app similar a la tuya pero en este caso es otro tipo de contenido, con otros propósitos, logré obtener lo de zypi, pero realmento me doy de topes con yourupload, pues no logro saber de donde salen los id, ya que tras una dura busqueda en el codigo fuente de la pagina no lo encuentro, realmente no comprendo como se genera, aparte, cuando se hace el streaming se genera lo que es
este link https://om136.cdn.oose.io/play/
y en el source viene sin el 136, de donde sale ese 136, o como se genera, se que vale para la ip, pero no comprendo de donde se obtiene y se valida
De antemano muchas gracias por todo

**Comment by jordyamc** [comment]
Haberlo dicho antes XD

Usa las herramientas de desarrollador de chrome en la pestaña Network, ahí te salen todas la peticiones que hace la página, busca sobre todo las peticiones que tengan respuestas con el header location
